name = "moontv-plus"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"
minify = true

# 自定义域名
routes = [
  { pattern = "tv.yunet.cfd", custom_domain = true }
]

# 静态资源配置
# Cloudflare Workers Assets 用于服务静态文件
[assets]
directory = ".open-next/assets"
binding = "ASSETS"

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "tvp"
database_id = "aef09eb6-6751-4313-835e-7b9a43dba989"

[vars]
NODE_ENV = "production"
BUILD_TARGET = "cloudflare"
NEXT_PUBLIC_STORAGE_TYPE = "d1"
USERNAME = "admin"
PASSWORD = "zxcv1111"
NEXT_PUBLIC_SITE_NAME = "MoonTV"
NEXT_PUBLIC_DISABLE_YELLOW_FILTER = "false"
